apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webapps
          image: klchandrika/webapps:${BUILD_NUMBER}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
spec:
  ports:
    - name: nginx
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: web            
            


